### ISSUE TITLE
it wont start?

### ISSUE THREAD

**Issue by aqweqwel123** [lulzyyy/lulzyOgar#1]
[root@vps81601 src]# forever index.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
module.js:341
    throw err;
    ^

Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/root/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
error: Forever detected script exited with code: 1

**Comment by AlexandriteErikParacelsus** [comment]
Do `npm install boom` in your terminal

**Comment by aqweqwel123** [comment]
okay ill try

**Comment by aqweqwel123** [comment]
[root@vps81601 src]# forever index.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Starting server...
/root/node_modules/ws/lib/WebSocketServer.js:44
    throw new TypeError('`port` or a `server` must be provided');
    ^

TypeError: `port` or a `server` must be provided
    at new WebSocketServer (/root/node_modules/ws/lib/WebSocketServer.js:44:11)
    at GameServer.start (/root/lulzyOgar/src/GameServer.js:579:25)
    at Object.<anonymous> (/root/lulzyOgar/src/index.js:25:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
error: Forever detected script exited with code: 1

**Comment by aqweqwel123** [comment]
nvm think i got it [root@vps81601 src]# forever index.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Starting server...
[Game] Listening on port 600

**Comment by lulzyyy** [comment]
wtf is boom module xD

**Comment by AlexandriteErikParacelsus** [comment]
I saw a module named `are-we-there-yet` before

**Comment by lulzyyy** [comment]
haha 

btw, remember, if you have 24/7 server(on vps for example) give me the link and I'll put it on c0nsume.me/private.php serverlist. MORE PEOPLE WILL BE PLAYING!

**Comment by segg21** [comment]
@lulzyy Wait.. Okay you are telling me you never heard of boom, but it never existed until this came along?

**Comment by lulzyyy** [comment]
I just didn't use boom module in ogar and I don''t know what is this

**Comment by lulzyyy** [comment]
btw nice to see you here @LegitSoulja, You're from Ogar Unlimited yea? good job! But sadly, I tried to implement it on c0nsume.me but it was very laggy with a lot of people...

**Comment by segg21** [comment]
Ogar-unlimited needs gas to run efficiently.
