### ISSUE TITLE
how do i connect this to my website using a vps?

### ISSUE THREAD

**Issue by aqweqwel123** [lulzyyy/lulzyOgar#2]

**Comment by lulzyyy** [comment]
what website? maybe iframe?
`<iframe  src="http://c0nsume.me/private.php?ip=YOUR_IP:600" style="border: 0; position:absolute; top:0; left:0; right:0; bottom:0; width:100%; height:100%" />`

change YOUR_IP to your ip address and put this in your page code
btw is your server public? give mi the link

**Comment by aqweqwel123** [comment]
can i get ur skype? or something i can private messaage you on?r

**Comment by lulzyyy** [comment]
let's just talk here

**Comment by aqweqwel123** [comment]
okay well i have not set my sight up yet but i have a ovh.com webhost and it keeps giving me a error so can u try to help me set it u p?

**Comment by lulzyyy** [comment]
what error?

**Comment by aqweqwel123** [comment]
thats why i wanted to skype so its instant
 so we can instant msg eachother

**Comment by aqweqwel123** [comment]
1 sec let me get back on it

**Comment by aqweqwel123** [comment]
[root@vps81601 ~]# cd lulzyOgar/src
[root@vps81601 src]# forever index.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Starting server...
[Game] Listening on port 600

**Comment by aqweqwel123** [comment]
no error now but how do i connect to it?

**Comment by lulzyyy** [comment]
what is your ip? https://www.whatismyip.com/

**Comment by aqweqwel123** [comment]
do i use my vps ip? or my actual ip

**Comment by lulzyyy** [comment]
vps

**Comment by aqweqwel123** [comment]
okay my vps ip is 149.56.141.57

**Comment by aqweqwel123** [comment]
do i need to go into the settings and pit 1 for vps?

**Comment by lulzyyy** [comment]
http://c0nsume.me/private.php?ip=149.56.141.57:600 start the server and tell me if it works

**Comment by aqweqwel123** [comment]
it is started

**Comment by lulzyyy** [comment]
hmm i cant connect...

**Comment by aqweqwel123** [comment]
exactly do i need to change vps to 1 in settings?

**Comment by lulzyyy** [comment]
maybe it's your firewall blocking the connection? what system do you use on your vps?

yeah try it and tell me port

**Comment by aqweqwel123** [comment]
is the port not 600?

**Comment by lulzyyy** [comment]
yes port is changing

**Comment by lulzyyy** [comment]
or try to change port to 443 maybe

**Comment by aqweqwel123** [comment]
how do i get port?

**Comment by lulzyyy** [comment]
change vps to 1 in settings
tell me what port from console ([Game] Listening on port xxx)

**Comment by aqweqwel123** [comment]
it doesnt tell me it gives me a error

**Comment by lulzyyy** [comment]
no wait it gives an error...

**Comment by aqweqwel123** [comment]
[root@vps81601 ~]# cd lulzyOgar/src
[root@vps81601 src]# node index.js
Starting server...
/root/node_modules/ws/lib/WebSocketServer.js:44
    throw new TypeError('`port` or a `server` must be provided');
    ^

TypeError: `port` or a `server` must be provided
    at new WebSocketServer (/root/node_modules/ws/lib/WebSocketServer.js:44:11)
    at GameServer.start (/root/lulzyOgar/src/GameServer.js:579:25)
    at Object.<anonymous> (/root/lulzyOgar/src/index.js:25:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
[root@vps81601 src]#

**Comment by lulzyyy** [comment]
try to change port to 443

**Comment by aqweqwel123** [comment]
keep settings for 1?

**Comment by lulzyyy** [comment]
no

**Comment by aqweqwel123** [comment]
k it says listing on port 443

**Comment by aqweqwel123** [comment]
[root@vps81601 src]# node index.js
Starting server...
[Game] Listening on port 443

**Comment by lulzyyy** [comment]
what system do you use on vps? windows? linux?

**Comment by aqweqwel123** [comment]
as in like what os?

**Comment by aqweqwel123** [comment]
Centos 6 (64 bits)

**Comment by lulzyyy** [comment]
hmm I'm using Debian 8 on my vps... 

ok turn off the sever and as administrator, type these commands

`service iptables save`
`service iptables stop`
`chkconfig iptables off`

it will disable the firewall... and then start the server again

**Comment by aqweqwel123** [comment]
like in the command?

**Comment by lulzyyy** [comment]
yea 

`service iptables save`
`service iptables stop`
`chkconfig iptables off`

**Comment by aqweqwel123** [comment]
and restart?

**Comment by lulzyyy** [comment]
after executing these commands start the server

**Comment by aqweqwel123** [comment]
can u do it for me? as in if i give u the info?

**Comment by aqweqwel123** [comment]
cause its not working

**Comment by lulzyyy** [comment]
ok

**Comment by aqweqwel123** [comment]
private message?

**Comment by aqweqwel123** [comment]
somewhere?'

**Comment by lulzyyy** [comment]
wait

**Comment by lulzyyy** [comment]
maybe just change the operation system to Debian 8? it will be much easier for me.

**Comment by aqweqwel123** [comment]
how do i change it>?

**Comment by aqweqwel123** [comment]
nvm i got it , its gonn a take some time tho

**Comment by lulzyyy** [comment]
in your vps settings, in ovh account

**Comment by aqweqwel123** [comment]
okay its doing it now

**Comment by aqweqwel123** [comment]
=can i get ur skype so no 1 else doesnt get the info for ssh?

**Comment by lulzyyy** [comment]
dont send me it yet, we will see what will happen with Debian

**Comment by lulzyyy** [comment]
after installing debian, intall node.js and lulzyOgar and start the server again on port 443

**Comment by aqweqwel123** [comment]
okay

**Comment by aqweqwel123** [comment]
does urs have bots? like minions?"

**Comment by lulzyyy** [comment]
should work fine

**Comment by lulzyyy** [comment]
normal bots are there, but minions not

**Comment by aqweqwel123** [comment]
dangit :( oh well

**Comment by lulzyyy** [comment]
using bots or minions on your server is useless as a lot of people will not want to play there

**Comment by aqweqwel123** [comment]
true

**Comment by aqweqwel123** [comment]
k its done

**Comment by lulzyyy** [comment]
Now start your server (you can left port 600 as default)

**Comment by aqweqwel123** [comment]
it removed evreything

**Comment by aqweqwel123** [comment]
so to make sure im doing it right want to do step by step with me?

**Comment by lulzyyy** [comment]
yes

**Comment by aqweqwel123** [comment]
okay
first do git clone then the link right?

**Comment by lulzyyy** [comment]
first execute these commands

`curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -`
`apt-get install -y nodejs`
`apt-get install -y build-essential`

**Comment by aqweqwel123** [comment]
it says command not found

**Comment by lulzyyy** [comment]
ok, 
apt-get install curl

**Comment by aqweqwel123** [comment]
root@vps81601:~# apt-get install curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package curl
root@vps81601:~#

**Comment by lulzyyy** [comment]
ok :P first
apt-get update

then

apt-get install curl

and rest

**Comment by aqweqwel123** [comment]
rest?

**Comment by lulzyyy** [comment]
`curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -`
`apt-get install -y nodejs`
`apt-get install -y build-essential`

**Comment by aqweqwel123** [comment]
it did evreything but curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -

**Comment by lulzyyy** [comment]
install it

**Comment by aqweqwel123** [comment]
it wont let me

**Comment by lulzyyy** [comment]
why?

**Comment by aqweqwel123** [comment]
root@vps81601:~# curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
-bash: curl: command not found

**Comment by lulzyyy** [comment]
did you install curl? 

apt-get install curl

**Comment by aqweqwel123** [comment]
-bash: curl: command not found
root@vps81601:~# ^C
root@vps81601:~# apt-get install curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libcurl3 libldap-2.4-2 librtmp1 libsasl2-2 libsasl2-modules
  libsasl2-modules-db libssh2-1
Suggested packages:
  libsasl2-modules-otp libsasl2-modules-ldap libsasl2-modules-sql
  libsasl2-modules-gssapi-mit libsasl2-modules-gssapi-heimdal
The following NEW packages will be installed:
  curl libcurl3 libldap-2.4-2 librtmp1 libsasl2-2 libsasl2-modules
  libsasl2-modules-db libssh2-1
0 upgraded, 8 newly installed, 0 to remove and 13 not upgraded.
Need to get 1,135 kB of archives.
After this operation, 2,361 kB of additional disk space will be used.
Do you want to continue? [Y/n]

**Comment by aqweqwel123** [comment]
y or n?

**Comment by lulzyyy** [comment]
y of course :D

**Comment by aqweqwel123** [comment]
okay

**Comment by aqweqwel123** [comment]
done

**Comment by lulzyyy** [comment]
`curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -`
`apt-get install -y nodejs`
`apt-get install -y build-essential`

**Comment by aqweqwel123** [comment]
i did all that

**Comment by lulzyyy** [comment]
now

`git clone git://github.com/lulzyyy/lulzyOgar.git lulzyOgar`
`cd lulzyOgar/src`
`npm install ws`
`npm install geoip-lite`
`npm install -g forever`

**Comment by lulzyyy** [comment]
oh first apt-get install git

**Comment by aqweqwel123** [comment]
k now what
start?

**Comment by lulzyyy** [comment]
node index.js

**Comment by lulzyyy** [comment]
node index.js

**Comment by aqweqwel123** [comment]
error]

**Comment by aqweqwel123** [comment]
root@vps81601:~/lulzyOgar/src# node index.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/lulzyOgar/src/modules/CommandList.js:8:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
root@vps81601:~/lulzyOgar/src#

**Comment by lulzyyy** [comment]
npm install request

**Comment by aqweqwel123** [comment]
root@vps81601:~/lulzyOgar/src# node index.js
Starting server...
[Game] Listening on port 600

**Comment by aqweqwel123** [comment]
yayy its working :) can anyone join now>?

**Comment by lulzyyy** [comment]
I joined

**Comment by lulzyyy** [comment]
I JOINED:D

**Comment by lulzyyy** [comment]
http://c0nsume.me/private.php?ip=149.56.141.57:600

**Comment by aqweqwel123** [comment]
okay and can i get this to go to my website?
like on my index.js?

**Comment by lulzyyy** [comment]
`<iframe src="http://c0nsume.me/private.php?ip=149.56.141.57:600" style="border: 0; position:absolute; top:0; left:0; right:0; bottom:0; width:100%; height:100%" />`

just put this in your site code

**Comment by lulzyyy** [comment]
are you here?

**Comment by aqweqwel123** [comment]
yes 1 sec

**Comment by lulzyyy** [comment]
do you use windows?

**Comment by aqweqwel123** [comment]
yep

**Comment by lulzyyy** [comment]
install program FileZilla. then you will be able to connect to your vps and send files, edit. gameserver.ini etc

**Comment by aqweqwel123** [comment]
i have it

**Comment by aqweqwel123** [comment]
http://alexdoesyt.esy.es/

**Comment by lulzyyy** [comment]
so set bigger map, and everything you want. I can add your server to list of private server on http://c0nsume.me and a lot of people will join your server

**Comment by aqweqwel123** [comment]
i can?

**Comment by aqweqwel123** [comment]
im not on putty anymore do iu need to be on it?

**Comment by lulzyyy** [comment]
just edit gameserver.ini and set everything

**Comment by aqweqwel123** [comment]
can i change the index?

**Comment by lulzyyy** [comment]
no just connect to your vps by filezilla

**Comment by aqweqwel123** [comment]
like is there a client file?

**Comment by lulzyyy** [comment]
no

**Comment by aqweqwel123** [comment]
actually can u help me setup ogar?

**Comment by aqweqwel123** [comment]
so i can get the client files?

**Comment by aqweqwel123** [comment]
and use that  instead?

**Comment by lulzyyy** [comment]
no you can't use client files because only I use them... you use only server files

**Comment by aqweqwel123** [comment]
oh okay :(

**Comment by aqweqwel123** [comment]
well can i use ogar? and u help me ? ill do a redirect back to ur site on my client html

**Comment by aqweqwel123** [comment]
index.html''

**Comment by lulzyyy** [comment]
connect to your server by filezilla and edit gameserver.ini

**Comment by aqweqwel123** [comment]
okay then what?>

**Comment by lulzyyy** [comment]
and restart server

**Comment by aqweqwel123** [comment]
what am i editing

**Comment by lulzyyy** [comment]
and the forever index.js

if you want server to auto restart

**Comment by aqweqwel123** [comment]
why did it kick me?

**Comment by aqweqwel123** [comment]
can u help me set up ogar?

**Comment by lulzyyy** [comment]
just edit gameserver.ini

there is everything

**Comment by aqweqwel123** [comment]
i honestly want minions with skins tho

**Comment by aqweqwel123** [comment]
so can u help me set that up?

**Comment by lulzyyy** [comment]
maybe i will add in a week i will see

**Comment by lulzyyy** [comment]
edit gameserver.ini what don't you understand

**Comment by aqweqwel123** [comment]
why do i need to ?

**Comment by lulzyyy** [comment]
to change settings?

**Comment by aqweqwel123** [comment]
i will do that later?

**Comment by lulzyyy** [comment]
as you want

**Comment by aqweqwel123** [comment]
http://play.ogarul.tk/?ip=149.56.141.57:443 i got this running

**Comment by aqweqwel123** [comment]
my ogar server

**Comment by lulzyyy** [comment]
noo it only works with my client

**Comment by aqweqwel123** [comment]
no i mean i got my ogar server this is totally diff files

**Comment by lulzyyy** [comment]
if you want to use http://play.ogarul.tk then download Ogar-Unlimited

**Comment by aqweqwel123** [comment]
i did ?

**Comment by lulzyyy** [comment]
ok

**Comment by aqweqwel123** [comment]
well ty for the help do u want me to put a link to ur server on my index?

**Comment by lulzyyy** [comment]
no

**Comment by lulzyyy** [comment]
no problem have fun ;)

**Comment by aqweqwel123** [comment]
1 more question

**Comment by aqweqwel123** [comment]
if i was to connect my files to a client folder how would i do so?

**Comment by aqweqwel123** [comment]
do you know?
