### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by Aarhunt** [lulzyyy/lulzyOgar#3]
module.js:327
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\downloads\lulzyOgar-master\src\modules\CommandList.js:8:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Press any key to exit...

I get this error all the time... Pleas help me

**Comment by lulzyyy** [comment]
open console and write

`npm install request`

then start server

**Comment by Aarhunt** [comment]
Doesn't work

**Comment by lulzyyy** [comment]
what error now?

**Comment by Aarhunt** [comment]
same one

**Comment by Aarhunt** [comment]
Console is CMD right?

**Comment by lulzyyy** [comment]
yes.

`npm install request` write this in console and press enter.

**Comment by Aarhunt** [comment]
Did it

**Comment by lulzyyy** [comment]
if it's installed you can't have same error omg

**Comment by Aarhunt** [comment]
module.js:327
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\downloads\lulzyOgar-master\src\modules\CommandList.js:8:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Press any key to exit...

This error

**Comment by lulzyyy** [comment]
i dont know how i can help you... it should work

**Comment by Aarhunt** [comment]
I'll try some stuff

**Comment by lulzyyy** [comment]
you just didn't install request module properly. idk why

**Comment by Ampflower** [comment]
NPM is not a valid command to the command prompt. That is the reason why it won't work.
